# Generated by Django 3.2.3 on 2021-05-20 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210520_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='editor',
        ),
        migrations.RemoveField(
            model_name='article',
            name='post',
        ),
    ]
